services:
  db-cliente:
    image: mysql:latest
    container_name: db-cliente
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=clientesdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpass
    volumes:
      - db-cliente-data:/var/lib/mysql
    networks:
      - srv-pedido-network

  srv-cliente:
    container_name: srv-cliente
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db-cliente
    networks:
      - srv-pedido-network
    volumes:
      - srv-cliente-data:/data/clientes
    environment:
      - MYSQL_URL=jdbc:mysql://db-cliente/clientesdb
      - MYSQL_DATABASE=clientesdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=adminpass
    ports:
      - "8085:8085"
    restart: always

networks:
  srv-pedido-network:

volumes:
    db-cliente-data:
    srv-cliente-data: